name: CI Workflow

on:
  push:
  pull_request:
    branches:
      - midterm

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setting up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Installing the dependencies
      run: |
        pip install -r requirements.txt

    - name: Running Tests
      run: |
        pytest test_health.py